In [2]:
import numpy as np
n1 = np.array([7,8,4,3,2])
print(n1)

[7 8 4 3 2]


In [ ]:

print(n1*2)

[14 16  8  6  4]


In [ ]:
n2= np.array([[1,2,3,4], [5,6,7,8]])

In [ ]:
print(n2)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
n4 = np.arange(50)

In [ ]:
print(n4)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]


# Pandas 

In [3]:
import pandas as pd
df = pd.read_csv('http://bit.ly/kaggletrain')
df

PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0              1         0       3  ...   7.2500   NaN         S
1              2         1       1  ...  71.2833   C85         C
2              3         1       3  ...   7.9250   NaN         S
3              4         1       1  ...  53.1000  C123         S
4              5         0       3  ...   8.0500   NaN         S
..           ...       ...     ...  ...      ...   ...       ...
886          887         0       2  ...  13.0000   NaN         S
887          888         1       1  ...  30.0000   B42         S
888          889         0       3  ...  23.4500   NaN         S
889          890         1       1  ...  30.0000  C148         C
890          891         0       3  ...   7.7500   NaN         Q

[891 rows x 12 columns]

In [5]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [6]:
#Data filtering
#Possible categories in a data column of a data frame - unique()
print(df['Survived'].unique())
print(df['Pclass'].unique())

[0 1]
[3 1 2]


In [7]:
#Number times unique value repeated in each column - value_counts()
print(df['Survived'].value_counts())
print(df['Pclass'].value_counts())

0    549
1    342
Name: Survived, dtype: int64
3    491
1    216
2    184
Name: Pclass, dtype: int64


In [8]:
#Seperate all survived and non-survived passengers
(df['Survived'] == 1).sum() 

342

In [9]:
df_survived = df[df['Survived'] == 1]

In [10]:
df_non_survived = df[df['Survived'] == 0]
df_non_survived.head()

PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0            1         0       3  ...   7.2500   NaN         S
4            5         0       3  ...   8.0500   NaN         S
5            6         0       3  ...   8.4583   NaN         Q
6            7         0       1  ...  51.8625   E46         S
7            8         0       3  ...  21.0750   NaN         S

[5 rows x 12 columns]

In [11]:
#Seperate all passengers from class 2
#No. of Male Travellers vs Female Travellers

df[df['Pclass'] == 2]

PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
9             10         1       2  ...  30.0708   NaN         C
15            16         1       2  ...  16.0000   NaN         S
17            18         1       2  ...  13.0000   NaN         S
20            21         0       2  ...  26.0000   NaN         S
21            22         1       2  ...  13.0000   D56         S
..           ...       ...     ...  ...      ...   ...       ...
866          867         1       2  ...  13.8583   NaN         C
874          875         1       2  ...  24.0000   NaN         C
880          881         1       2  ...  26.0000   NaN         S
883          884         0       2  ...  10.5000   NaN         S
886          887         0       2  ...  13.0000   NaN         S

[184 rows x 12 columns]

In [12]:
df['Sex'].value_counts()

male      577
female    314
Name: Sex, dtype: int64

In [13]:
df[df['Sex'] == 'male']

PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0              1         0       3  ...   7.2500   NaN         S
4              5         0       3  ...   8.0500   NaN         S
5              6         0       3  ...   8.4583   NaN         Q
6              7         0       1  ...  51.8625   E46         S
7              8         0       3  ...  21.0750   NaN         S
..           ...       ...     ...  ...      ...   ...       ...
883          884         0       2  ...  10.5000   NaN         S
884          885         0       3  ...   7.0500   NaN         S
886          887         0       2  ...  13.0000   NaN         S
889          890         1       1  ...  30.0000  C148         C
890          891         0       3  ...   7.7500   NaN         Q

[577 rows x 12 columns]

In [14]:
#To find out all existing null points
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [15]:
df.shape

(891, 12)

In [16]:
#to remove nulls 
df['Age'].mean()

29.69911764705882

In [17]:
#fillna() - to fill the void or null spaces in a data column
df['Age'].fillna(29.70)

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ... 
886    27.0
887    19.0
888    29.7
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64

In [18]:
#groupby() - to group the dataframes based upon a defined category
df.groupby('Sex')['Age'].mean()

Sex
female    27.915709
male      30.726645
Name: Age, dtype: float64

In [19]:
df.groupby('Pclass')['Age'].mean()

Pclass
1    38.233441
2    29.877630
3    25.140620
Name: Age, dtype: float64

In [20]:
dfx = df[df['Pclass'] == 1]
dfy = df[df['Pclass'] == 2]
dfz = df[df['Pclass'] == 3]

In [21]:
dfx['Age'] = dfx['Age'].fillna(38.23)
dfy['Age'] = dfy['Age'].fillna(29.87)
dfz['Age'] = dfz['Age'].fillna(25.14)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documen

In [22]:
#concat() - to combine multiple data frame
df2 = pd.concat((dfx,dfy,dfz),ignore_index=True)

In [23]:
df2.head()

PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0            2         1       1  ...  71.2833   C85         C
1            4         1       1  ...  53.1000  C123         S
2            7         0       1  ...  51.8625   E46         S
3           12         1       1  ...  26.5500  C103         S
4           24         1       1  ...  35.5000    A6         S

[5 rows x 12 columns]

In [24]:
df2.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [25]:
df2['Sex'].mode()

0    male
dtype: object

In [26]:
df2.groupby('Pclass')['Sex'].value_counts()

Pclass  Sex   
1       male      122
        female     94
2       male      108
        female     76
3       male      347
        female    144
Name: Sex, dtype: int64

In [27]:
#Droping the column with higher numbers of null value
df3 = df2.drop('Cabin',axis='columns')
df3.head()

PassengerId  Survived  Pclass  ...    Ticket     Fare  Embarked
0            2         1       1  ...  PC 17599  71.2833         C
1            4         1       1  ...    113803  53.1000         S
2            7         0       1  ...     17463  51.8625         S
3           12         1       1  ...    113783  26.5500         S
4           24         1       1  ...    113788  35.5000         S

[5 rows x 11 columns]

In [28]:
df3.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       2
dtype: int64

In [29]:
#dropna() - drops or remove any row or a column having null values
df4 = df3.dropna(axis='rows')

In [30]:
print(df3.shape)
print(df4.shape)

(891, 11)
(889, 11)
